### ISSUE TITLE
Get an error if i try to activate the plugin. Version 5.9.0 Pro

### ISSUE THREAD

**Issue by ashk0re** [nextgenthemes/advanced-responsive-video-embedder#12]
Parse error: syntax error, unexpected '=', expecting ')' in /www/htdocs/XXXXX/wp-content/plugins/advanced-responsive-video-embedder-dev/admin/class-advanced-responsive-video-embedder-admin.php on line 577

**Comment by nextgenthemes** [comment]
Thanks for testing, this is fixed now.
