### ISSUE TITLE
Invalid HTML in vimeo iframe code

### ISSUE THREAD

**Issue by standardspace** [nextgenthemes/advanced-responsive-video-embedder#13]
In order to achieve valid html I'l suggest a change to the create_iframe function to remove the folowing attributes:
webkitallowfullscreen
mozallowfullscreen
frameborder
scrolling

ie:

	/**
	 *
	 *
	 * @since    2.6.0
	 */
	public function create_iframe( $url, $lazyload = false, $fullscreen = true ) {

		return sprintf(
			'<iframe%s class="%s" %s="%s" %s></iframe>',
			( $lazyload ) ? sprintf( ' id="arve-iframe-%d"', $lazyload ) : '',
			( $lazyload ) ? 'arve-inner arve-hidden' : 'arve-inner',
			( $lazyload ) ? 'data-src' : 'src',
			str_replace( 'jukebox?list%5B0%5D', 'jukebox?list[]', esc_url( $url ) ), //* Fix escaped brackets we don't want escaped for dailymotion playlists
			( $fullscreen ) ? 'allowfullScreen' : ''
		);
	}

**Comment by nextgenthemes** [comment]
I removed everything but frameborder="0" and allowfullscreen. Youtubes offical embed codes still use frameborder, and for a good reason I guess. I keep it for now.
