### ISSUE TITLE
Tag missing releases

### ISSUE THREAD

**Issue by khromov** [nextgenthemes/advanced-responsive-video-embedder#18]
Hi,

The latest version of ARVE is 6.3.6 according to WordPress.org:
https://wordpress.org/plugins/advanced-responsive-video-embedder/changelog/

However, the latest tag from the 6.3.X branch here on GitHub is 6.3.4:
https://github.com/nextgenthemes/advanced-responsive-video-embedder/releases

Can you please make sure to tag every release for people that are using Composer to version mange their WordPress plugins? 

PS.
Could you also make sure to create tags for upcoming versions on the WordPress.org SVN? 
http://plugins.svn.wordpress.org/advanced-responsive-video-embedder/

**Comment by nextgenthemes** [comment]
I don't think am not going to create tags in SVN. I just use it as a dump and put the current stable version in trunk. Why do you want me to do it?

I update beta versions here in Github before wordpress.org release, so I try to tag only the current stable versions here for composer.

**Comment by khromov** [comment]
There are two ways to version manage wordpress plugins with Composer - Either using http://wpackagist.org/ (which scrapes the WordPress.org SVN, and doesn't properly pick up tags properly since you don't create tags) or you can use GitHub, where it picks up the releases that are created on GitHub.

So, if you can at least tag both stable and beta releases on GitHub we can at least still use Composer to version manage ARVE. :smiley_cat:

**Comment by nextgenthemes** [comment]
I think I got a routine in tagging all versions now.

**Comment by khromov** [comment]
Awesome! :+1:
