### ISSUE TITLE
echo wp_oembed_get( $video_url);

### ISSUE THREAD

**Issue by ollybowman** [nextgenthemes/advanced-responsive-video-embedder#21]
Should this be working with wp_oembed_get?

Currently on my install it's creating the correct width, but the height is not changing and the video is not scaling.

**Comment by nextgenthemes** [comment]
This plugin does not really use oembed in the way WordPress does. I get the title and the thumbnails via oembed but not the dimensions. The the height specifically is calculated with a CSS technique involving only the aspect ratio so there is no height you can get hold of in php code at all.

What is it you want to do?

**Comment by ollybowman** [comment]
https://codex.wordpress.org/Function_Reference/wp_oembed_get

I'm using this on my homepage, where $video_url is a youtube url:

`echo wp_oembed_get( $video_url);`

which returns this in the html:-

`<iframe class="wp-embedded-content" sandbox="allow-scripts" security="restricted" width="980" height="551" src="https://www.youtube.com/embed/gBQTj1O34tw?feature=oembed#?secret=2qaww7GAme" data-secret="2qaww7GAme" frameborder="0"></iframe>`

is there any way of making this responsive as well?

**Comment by nextgenthemes** [comment]
Can you explain what you are trying do do? Because this has nothing to do with ARVE anymore. Sure you can make that responsive like for example with CSS and div wrapper like ARVE is doing.

**Comment by nextgenthemes** [comment]
Closing this because no respnose
