### ISSUE TITLE
Fatal error in admin file (class-arve-admin.php)

### ISSUE THREAD

**Issue by andizer** [nextgenthemes/advanced-responsive-video-embedder#22]
I am getting the next fatal error: `Fatal error: Can't use function return value in write context in .../advanced-responsive-video-embedder/admin/class-arve-admin.php on line 723`

I guess it's better to do:
```
$user_meta = get_user_meta( get_current_user_id(), 'arve_dismiss_pro_notice' );
if( ! empty( $user_meta ) ) {
    return;
}
```

**Comment by nextgenthemes** [comment]
Thanks @andizer I now included your solution to this issue.
