### ISSUE TITLE
Changelog it out-dated and inconsistent

### ISSUE THREAD

**Issue by essensx** [nextgenthemes/advanced-responsive-video-embedder#27]
I have version 6.5.0 installed but can't seem to find it in the changelog. Also the latest version is 8.0.2 but i only see until 8.0.0 in the changelog.

**Comment by nextgenthemes** [comment]
The most up to date changelog is [hosted on wp.org](https://wordpress.org/plugins/advanced-responsive-video-embedder/changelog/), it includes 8.0.2.

I may have forgot 6.5.0 since I am long past that and do not support old versions I will not try to find out whats missing.
