### ISSUE TITLE
arve_get_pro_ad tries to load file that doesn't exist.

### ISSUE THREAD

**Issue by johnduhart** [nextgenthemes/advanced-responsive-video-embedder#28]
`arve_get_pro_ad` is trying to load `advanced-responsive-video-embedder/readme/description-features-pro.html` but that file was removed in this commit: https://github.com/nextgenthemes/advanced-responsive-video-embedder/commit/ceab42d84a410d163afbb90f3a6db755db57e6ce#diff-d6ab20731fd26b104808cf20c27532a2

**Comment by nextgenthemes** [comment]
Are you updating your plugin with git? Because this is is already fixed in the current version thats on wp.org.

I will push a update here soon with my latest dev version.

**Comment by johnduhart** [comment]
Looks like the plugin was not up to date, when I checked GitHub I still saw the offending line of code. I didn't realize the code here was not kept in sync with wp.org. I will update the plugin and close if it resolves the issue.

**Comment by nextgenthemes** [comment]
Generally it is kept up to date but the last time I just pushed a quick fix for this critical error to wp.org only.
