### ISSUE TITLE
Any issue with styling for latest update?

### ISSUE THREAD

**Issue by sk29110** [nextgenthemes/advanced-responsive-video-embedder#31]
I recently update the plugin and getting the big padding under the video.
Do you happen to know why?

https://i.imgur.com/5xz1jol.png

you can see the live here http://scenekunstskoler.dk

**Comment by nextgenthemes** [comment]
I see a error that your main stylesheet of your theme cannot be loaded. The ARVE styles also seem not be loaded. Could be something about caching.

**Comment by nextgenthemes** [comment]
By latest update you mean the latest version from wp.org? This repo is containing completely unstable alpha code on master, do not use it.

**Comment by nextgenthemes** [comment]
Closing this because of no reply. By looking at your site it seems this is fixed. If you have any more questions like this please use https://nextgenthems.com/support
