### ISSUE TITLE
Problem while Activating the Plug-in.

### ISSUE THREAD

**Issue by ayradc** [nextgenthemes/advanced-responsive-video-embedder#33]
**Fatal error**: Call to undefined function Nextgenthemes\ARVE\enqueue() in C:\xampp\htdocs\wp\wp-content\plugins\advanced-responsive-video-embedder-9\admin\**functions-admin.php** on line **659**

**Comment by nextgenthemes** [comment]
You seem to use the version from the v9 branch from Github. Its currently in pre alpha state. And not intended to be used yet. Please use the current stable versions from https://wordpress.org/plugins/advanced-responsive-video-embedder/
