### ISSUE TITLE
Widget support?

### ISSUE THREAD

**Issue by strarsis** [nextgenthemes/advanced-responsive-video-embedder#36]
Currently a shortcode has to be used. It would be nice to have a full ARVE widget.

**Comment by nextgenthemes** [comment]
You actually can use shortcodes in the text widget. So this is a easy and simple way to have ARVE inside a widget.

Anything specific you are looking for?

I am currently working on a Gutenberg Block and WordPress its on is way to have "Block Areas" Blocks as Widgets or something like that as experimental feature in Gutenberg. I have not looked that deep into it but so if you use the new Block Editor (Gutenberg) then this may solve itself by having the new GB Block act as a Widget.

**Comment by strarsis** [comment]
This should be used for a site that still uses the Classic Editor. The core video widget/shortcode doesn't offer muted autoplay (which is required for autoplay in Chrome and other browsers since 2017), this is basically all I want to add. And the poster is not displayed with the core video widget, for whatever reason.

**Comment by nextgenthemes** [comment]
You closed this because you are fine with using shortcodes in the text widget?

I will keep this open to remind me to look into how ARVE can just take over the core video widget.

**Comment by strarsis** [comment]
@nextgenthemes: Right, I currently use a shortcode widget which itself uses a shortcode for adding the video.
