### ISSUE TITLE
Wordpress version compatibility problem

### ISSUE THREAD

**Issue by paussus** [nextgenthemes/advanced-responsive-video-embedder#44]
Hi,

  first of all, thanks for the plugin!

  I have noticed that the plugin states in the [wordpress.org page](https://wordpress.org/plugins/advanced-responsive-video-embedder/) that it works in 4.4.0 and higher, but the latest version uses [WP_Error::has_errors()](https://developer.wordpress.org/reference/classes/wp_error/has_errors/#changelog) that was introduced in 5.1.0 and crashes on older versions. It's [this line](https://github.com/nextgenthemes/advanced-responsive-video-embedder/blob/73a3471c242ad28f7c27f72e94b9fb1fb17d84f7/php/functions-shortcodes.php#L95).

Thanks
Pau

**Comment by nextgenthemes** [comment]
I actually have not tested old WP versions for a very long time, I have automated tests running for the 2 latest versions and PHP back to 5.6. If it's just about that `WP_Error::has_errors()` that is not an issue, I just removed the code. The check was actually not needed at all and made the code simpler.

But I tried to test 4.4.24 and php 5.6, but I get an error in /symphony/yaml that is probably related to phpunit and the testing env I use for the other tests. I am not really interested in supporting outdated WP versions unless you want to help me get the test working. If its just that function the plugin will probably work with 4.4 on the next update. Could you try the latest from `master`?

Why do you need to run such an outdated WP version?

**Comment by paussus** [comment]
There's no real need to use an outdated version, it's an old and simple website, and 4.9 still receives security updates. But I'm not really interested in supporting outdated wp versions, and I'm not asking for that either, I know I will have to update sometime.

Thanks for the update.

**Comment by nextgenthemes** [comment]
Even though you later said you do not need an older version any more I got a bit obsessed trying older versions and I got `4.9.16` to pass the unit tests by skipping just one Dailymotion test. I adjusted the required tag to 4.9.16. My guess would be that in the real word the error for that one test is just ignored and even Dailymotion works fine.
