### ISSUE TITLE
custom thumbnail per video

### ISSUE THREAD

**Issue by lpirl** [nextgenthemes/advanced-responsive-video-embedder#9]
First, thanks for this really well done plug-in!

Second, do you think there could be a functionality to set a custom thumbnail per embed in the next release?

The functionality is probably only a small extension to `mode="thumbnail"` and I can imagine that it's relatively simple to add this unique feature.

The markup could look like this:
```
[youtube id="myvideoid" mode="thumbnail" thumbnail="/wp-content/uploads/example.jpg"]
```
or even this:
```
[youtube id="myvideoid" mode="thumbnail" thumbnail="MyAttachmentName"]
```
Thanks!

**Comment by rubendibattista** [comment]
This would be awsome! I also would like to have the possibility to set a custom thumbnail for the thumbnail mode and a custom background image for the lazyload.

**Comment by nextgenthemes** [comment]
This is now part of the [pro addon](https://nextgenthemes.com/downloads/advanced-responsive-video-embedder-pro/) thats currently in testing. If you have any issues let me know.
